### ISSUE TITLE
Cuando es llamado Update()?

### ISSUE THREAD

**Issue by Trisky** [Trisky/2016_2C_K3072_Grupo-MS#3]
@mysery @rejurime
Estoy intentando hacer que mi autito acelere, por ahora lo unico que hice fue programar como sería el movimiento del mismo

En GameModel.cs, dentro de Update(), llamo a 
`AutoJugador.Update(Input);` _(linea 195)_

La idea es que esto reciba el input de registrado desde el teclado y mouse de ese "frame" y accione  acorde a lo programado.

El problema es que no funciona, y no veo por qué.
Para ver lo que hace, iniciar el juego y apretar la tecla o para salir de la cámara en modo dios y pasar a la camara en tercera persona del mesh, luego apretar w, esto debería incrementar la velocidad (mostrada en el margen superior izquierdo) en 10 unidades por cada vez que W es apretada, pero esto funciona solo una vez :(

Según lo que yo entiendo Update() es llamada una vez por frame "transcurrido" y por lo tanto AutoJugador.Update(Input); también. 
En que le estoy pifiando?

**Comment by mysery** [comment]
En ningún lado veo que actualices las matrices de transformación, eso debes hacerlo en render antes de enviar de hacer `mesh.render()`.
Recordá no solo actualizar los parámetros internos y no trata de no utilizar el move.
Saludos.

**Comment by Trisky** [comment]
genial, entiendo que por eso no se mueve el mesh del camionsito, pero si con la duda: ¿Por que cuando sigo apretando W, la "velocidad"(el int que aparece arriba a la izquierda) a la izquierda no sigue subiendo?

> no trata de no utilizar el move.

Supongo que intentaste decirme que no use el move, no? jaja.

**Comment by mysery** [comment]
Mira un poco tu código:
`if (this.AvanceMax > this.Velocidad)`
no te dice nada?

Eso mismo, el con el move perdés el control de la matriz.

**Comment by Trisky** [comment]
Ups. Que salame. Gracias.
